
import { Review, Feature, ComparisonFeature, TechStackItem } from './types';
import { SiReact, SiNodedotjs, SiTypescript, SiTailwindcss, SiFramer } from 'react-icons/si';
import { FaGlobe, FaCogs, FaProjectDiagram, FaChalkboardTeacher } from 'react-icons/fa';
import { COURSES as COURSES_LIST } from './data/courses';

export const COURSES = COURSES_LIST;

export const REVIEWS: Review[] = [
  { name: 'Sarah L.', location: 'USA', avatar: '', review: 'This platform transformed my career. The interactive lessons are a game-changer!', stars: 5 },
  { name: 'Ahmed Khan', location: 'Dhaka, Bangladesh', avatar: '', review: 'Finally, a world-class learning platform with relevant local context. Highly recommended!', stars: 5 },
  { name: 'Michael B.', location: 'UK', avatar: '', review: 'The interactive demos make complex topics so easy to understand.', stars: 4 },
  { name: 'Fatima Chowdhury', location: 'Chittagong, Bangladesh', avatar: '', review: 'I learned React faster here than on any other platform. The projects are amazing.', stars: 5 },
  { name: 'Carlos G.', location: 'Spain', avatar: '', review: 'Incredible content, and it\'s free! The quality rivals paid bootcamps.', stars: 5 },
  { name: 'Priya Sharma', location: 'India', avatar: '', review: 'The visual learning approach really helps concepts stick.', stars: 4 },
  { name: 'Kenji Tanaka', location: 'Japan', avatar: '', review: 'As a visual learner, the progress trees are fantastic. Nothing else like it.', stars: 5 },
  { name: 'Aisha Diallo', location: 'Nigeria', avatar: '', review: 'The open-source nature is a huge plus. It feels community-driven.', stars: 5 },
  { name: 'Liam Murphy', location: 'Ireland', avatar: '', review: 'I was stuck in a tutorial loop for months. Open4Code\'s project-based tracks finally got me building real applications.', stars: 5 },
  { name: 'Isabella Rossi', location: 'Italy', avatar: '', review: 'The quality of the content is exceptional, especially for a free platform.', stars: 4 },
  { name: 'Omar Al-Farsi', location: 'UAE', avatar: '', review: 'The mobile experience is flawless, allowing me to learn on my commute.', stars: 5 },
  { name: 'Chloe Dubois', location: 'France', avatar: '', review: 'The AI learning aids provide summaries and tips that are surprisingly helpful.', stars: 4 },
];

export const FEATURES: Feature[] = [
  { Icon: FaGlobe, title: 'Interactive Learning', description: 'Engage with hands-on exercises, live code playgrounds, and quizzes that provide instant feedback.' },
  { Icon: FaProjectDiagram, title: 'Project-Based Tracks', description: 'Build real-world projects to solidify your skills and create a portfolio that stands out.' },
  { Icon: FaCogs, title: 'Visual Progress Tracking', description: 'Navigate your learning journey with our unique skill trees, making progress feel rewarding.' },
  { Icon: FaChalkboardTeacher, title: 'Expert-Crafted Content', description: 'Learn from industry professionals with up-to-date curriculum covering in-demand technologies.' },
];

export const COMPARISON_FEATURES: ComparisonFeature[] = [
  { feature: 'Interactive 3D Demos', open4code: true, others: false, description: 'Engage with concepts like never before through our unique, hands-on 3D visualizations.' },
  { feature: 'Truly Project-Based', open4code: true, others: false, description: 'Build a portfolio of real-world projects, not just isolated code snippets.' },
  { feature: '100% Free, No Ads', open4code: true, others: false, description: 'World-class education should be accessible to all, without hidden fees or distractions.' },
  { feature: 'Open Source Community', open4code: true, others: false, description: 'Learn, contribute, and grow with a transparent, community-driven platform.' },
  { feature: 'AI-Powered Learning Aids', open4code: true, others: false, description: 'Get smart notes, tips, and memory aids generated by AI to accelerate your learning.' },
  { feature: 'Visual Skill Trees', open4code: true, others: false, description: 'Track your progress in a rewarding and intuitive way with our unique skill tree interface.' },
];

export const TECH_STACK: TechStackItem[] = [
  { name: 'React', Icon: SiReact, color: '#36A18B' },
  { name: 'TypeScript', Icon: SiTypescript, color: '#3178C6' },
  { name: 'Tailwind CSS', Icon: SiTailwindcss, color: '#38BDF8' },
  { name: 'Framer Motion', Icon: SiFramer, color: '#0055FF' },
  { name: 'Node.js', Icon: SiNodedotjs, color: '#9F5255' },
];
